name: Project Board Automation

on:
  issues:
    types: [opened, closed, reopened, assigned]
  pull_request:
    types: [opened, closed, reopened, merged, ready_for_review, converted_to_draft]

jobs:
  project-board:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Move new issues to Todo
        if: github.event.action == 'opened' && github.event.issue
        uses: actions/github-script@v7
        with:
          script: |
            // Add issue to project board in "Todo" column
            // This is a placeholder - actual implementation would depend on your project board setup
            console.log('New issue opened:', context.payload.issue.number);

      - name: Move assigned issues to In Progress
        if: github.event.action == 'assigned' && github.event.issue
        uses: actions/github-script@v7
        with:
          script: |
            // Move issue to "In Progress" column when assigned
            console.log('Issue assigned:', context.payload.issue.number);

      - name: Move closed issues to Done
        if: github.event.action == 'closed' && github.event.issue
        uses: actions/github-script@v7
        with:
          script: |
            // Move issue to "Done" column when closed
            console.log('Issue closed:', context.payload.issue.number);

      - name: Move PR to Review
        if: github.event.action == 'ready_for_review' && github.event.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            // Move PR to "Review" column when ready for review
            console.log('PR ready for review:', context.payload.pull_request.number);

      - name: Move merged PR to Done
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions/github-script@v7
        with:
          script: |
            // Move PR to "Done" column when merged
            console.log('PR merged:', context.payload.pull_request.number);

  milestone-management:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add to current milestone
        if: github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: milestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'due_on',
              direction: 'asc'
            });

            if (milestones.length > 0) {
              const currentMilestone = milestones[0];
              const issueNumber = context.payload.issue?.number || context.payload.pull_request?.number;
              
              if (issueNumber) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  milestone: currentMilestone.number
                });
                
                console.log(`Added to milestone: ${currentMilestone.title}`);
              }
            }